// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Response { total_cpu_load: number, cpu_temp: number, gpu_temp: number, total_gpu_load: number, total_ram_load: number, total_vram_load: number, cpu_model: string, gpu_model: string, }